# Site settings
title: Ashish Yadav
description: Blog for photography
keywords: Modern, Blogging, Fun, Photography, Fine arts
author: Manas Kashyap
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
